# Base downloader stage with common setup
FROM ollama/ollama AS base-downloader
COPY <<EOF /init-models.sh
#!/bin/bash
set -e

# Get model params
original_model=\$1
final_name=\$2

# Start ollama in the background
ollama serve &
OLLAMA_PID=\$!
sleep 10

# Download and rename model
echo "Downloading \$final_name ..."
ollama pull \$original_model > /dev/null 2>&1 && \
ollama cp \$original_model \$final_name && \
ollama rm \$original_model

# Cleanup
kill \$OLLAMA_PID
sleep 5
EOF
RUN chmod +x /init-models.sh

# Separate stage for each model
FROM base-downloader AS llama-70b-downloader
RUN /init-models.sh "llama3.3:70b-instruct-q4_0" "llama3:70b"

FROM base-downloader AS hermes-70b-downloader
RUN /init-models.sh "hermes3:70b-llama3.1-q4_0" "hermes3:70b"

FROM base-downloader AS llama-8b-downloader
RUN /init-models.sh "llama3.1:8b-instruct-q8_0" "llama3:8b"

FROM base-downloader AS hermes-8b-downloader
RUN /init-models.sh "hermes3:8b-llama3.1-q8_0" "hermes3:8b"

FROM base-downloader AS llama-3b-downloader
RUN /init-models.sh "llama3.2:3b-instruct-q8_0" "llama3:3b"

FROM base-downloader AS hermes-3b-downloader
RUN /init-models.sh "hermes3:3b-llama3.2-q8_0" "hermes3:3b"

# Final image
FROM ollama/ollama

# Add non-root user
RUN groupadd -r -g 65532 ollama && \
    useradd -r -m -u 65532 -g ollama ollama

# create diretory
RUN mkdir -p /home/ollama/.ollama/models/manifests/registry.ollama.ai && mkdir -p /home/ollama/.ollama/models/blobs && chown -R ollama:ollama /home/ollama/.ollama/

# Copy models from each builder
COPY --from=llama-70b-downloader /root/.ollama/models /home/ollama/.ollama/models
COPY --from=hermes-70b-downloader /root/.ollama/models /home/ollama/.ollama/models
COPY --from=llama-8b-downloader /root/.ollama/models /home/ollama/.ollama/models
COPY --from=hermes-8b-downloader /root/.ollama/models /home/ollama/.ollama/models
COPY --from=llama-3b-downloader /root/.ollama/models /home/ollama/.ollama/models
COPY --from=hermes-3b-downloader /root/.ollama/models /home/ollama/.ollama/models

USER 65532:65532